---
title: Key Binding State Machine
---

stateDiagram
	direction LR

	counter: Repeat Counter
	exact: Exact Match
	longer: Longer Match Exists
	no_match: No Matches

	[*]      --> counter
	counter  --> counter  : digit
	counter  --> exact    : key
	counter  --> longer   : key
	counter  --> no_match : key
	longer   --> exact    : key
	longer   --> no_match : key
	exact    --> [*]
	no_match --> [*]

