```mermaid
  graph LR
      mutt_file_fopen             --> mutt_file_fopen_full
      mutt_file_fopen_full        --> fdopen
      mutt_file_fopen_full        --> fopen
      mutt_file_fopen_masked      --> mutt_file_fopen_masked_full
      mutt_file_fopen_masked_full --> mutt_file_fopen_full
```
