syntax match black   "===\+"
syntax match blue    "offset \d\+"
syntax match cyan    "MT_COLOR_\i\+"
syntax match green   "search (\d\+)"
syntax match grey    "\[plain\]"
syntax match magenta "\d\+ bytes, \d\+ cols"
syntax match red     "\[[0-9]\+-[0-9]\+\]"
syntax match yellow  "text (\d\+)"
