#!/bin/bash

WATCH="pager/line.c pager/line.h"
STAMP_THIS=$(mktemp)
STAMP_CODE=$(mktemp)
WAIT=1

touch "$STAMP_THIS"
touch -d "1 year ago" "$STAMP_CODE"

while :; do
	NEWER=0
	for i in $WATCH; do
		if [ $i -nt "$STAMP_CODE" ]; then
			NEWER=1
			break;
		fi
	done
	if [ $NEWER = 1 ]; then
		sleep 0.5
		touch "$STAMP_CODE"
		clear
		gcc $EXTRA_CFLAGS -I. -o jim pager/line.c  libmutt.a libcore.a libemail.a libaddress.a libnotmuch.a libconfig.a libmutt.a -lidn2 -lpcre2-8 -fsanitize=address && ./jim 1.mbox
		echo
	fi

	[ "$0" -nt "$STAMP_THIS" ] && exec "$0"

	sleep $WAIT
done

