s/\<OP_ATTACH_COLLAPSE\>/OP_ATTACHMENT_COLLAPSE/g
s/\<OP_ATTACH_VIEW_MAILCAP\>/OP_ATTACHMENT_VIEW_MAILCAP/g
s/\<OP_ATTACH_VIEW_PAGER\>/OP_ATTACHMENT_VIEW_PAGER/g
s/\<OP_ATTACH_VIEW_TEXT\>/OP_ATTACHMENT_VIEW_TEXT/g
