QuickhlManualAdd! \<cs\i\+\>
QuickhlManualAdd! \<helpbar\i\+\>
QuickhlManualAdd! \<ibar\i\+\>
QuickhlManualAdd! \<index\i\+\>
QuickhlManualAdd! \<main\i\+\>
QuickhlManualAdd! \<menu\i\+\>
QuickhlManualAdd! \<msgwin\i\+\>
QuickhlManualAdd! \<mutt\i\+\>
QuickhlManualAdd! \<notify\i\+\>
QuickhlManualAdd! \<pager\i\+\>
QuickhlManualAdd! \<sb\i\+\>
QuickhlManualAdd! \<window\i\+\>
